version: '3.3'
services:
    docker-ripper:
        container_name: Ripper
        volumes:
            - '/path/to/config/:/config:rw'
            - '/path/to/rips/:/out:rw'
        devices:
            - '/dev/sr0:/dev/sr0'
            - '/dev/sg0:/dev/sg0'
        ports:
            - 'port:9090' # optional - port for the integrated web ui
        environment:
            - PREFIX=OPTIONAL_WEB_UI_PATH_PREFIX # optional - path prefix for the integrated web ui
            - USER=OPTIONAL_WEB_UI_USERNAME # optional - user name for the integrated web ui (requires PASS to be set)
            - PASS=OPTIONAL_WEB_UI_PASSWORD # optional - password for the integrated web ui (requires USER to be set)
        privileged: true # optional - only use when your drive is not detected inside the container
        image: rix1337/docker-ripper
