name: Build Image

on: [push, pull_request, workflow_dispatch]

env:
  ENDPOINT: "rix1337/docker-ripper"
  BRANCH: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Build image
        run: |
          docker build --no-cache -t ${{ github.sha }} .

      - name: Tag image
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) }}
        run: |
          docker tag ${{ github.sha }} ${ENDPOINT}:latest

      - name: Credential check
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) }}
        run: |
          echo "DOCKERUSER=${{ secrets.DOCKERUSER }}" >> $GITHUB_ENV
          echo "DOCKERPASS=${{ secrets.DOCKERPASS }}" >> $GITHUB_ENV
          if [[ "${{ secrets.DOCKERUSER }}" == "" && "${{ secrets.DOCKERPASS }}" == "" ]]; then
            echo "::error::Push credential secrets missing."
            exit 1
          fi

      - name: Login to DockerHub
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.DOCKERUSER && env.DOCKERPASS }}
        run: |
          echo ${{ secrets.DOCKERPASS }} | docker login -u ${{ secrets.DOCKERUSER }} --password-stdin

      - name: Push tags to DockerHub
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.DOCKERUSER && env.DOCKERPASS }}
        run: |
          docker push ${ENDPOINT}:latest
